export const DATA_QUALITY_REASON_CODES = [
  "CONFIRMED_FRESH",
  "CLAIMED_SOURCE_ONLY",
  "FIELD_UNCONFIRMED",
  "FIELD_UNKNOWN",
  "FIELD_CONFLICTING",
  "FIELD_AGING",
  "FIELD_STALE",
  "FIELD_EXPIRED",
  "NO_EVIDENCE",
  "MULTIPLE_AGREEING_EVIDENCE",
  "CRITICAL_MUST_FIELD_UNKNOWN",
  "CRITICAL_FIELD_STALE",
] as const;

export type DataQualityReasonCode = (typeof DATA_QUALITY_REASON_CODES)[number];

export const RECOMMENDED_CHECK_CODES = [
  "REFRESH_PRICE",
  "VERIFY_AVAILABILITY",
  "VERIFY_FINANCING_APPLICABILITY",
  "VERIFY_INITIAL_PAYMENT",
  "RESOLVE_SOURCE_CONFLICT",
  "VERIFY_HANDOVER_DATE",
  "VERIFY_GAS_CONNECTION",
  "VERIFY_FIELD",
] as const;

export type RecommendedCheckCode = (typeof RECOMMENDED_CHECK_CODES)[number];
